# Book settings

title: ""
logo: ../logo/logo.svg
author: Joris Paret and Daniele Coslovich

# Do not execute the notebooks
execute:
  execute_notebooks: "off"

# GitHub repository
repository:
  url: https://github.com/jorisparet/partycls
  path_to_book: tutorial
  branch: master

# Binder
launch_buttons:
  notebook_interface: https://mybinder.org

# GitHub buttons
html:
  favicon: ../logo/favicon.svg
  use_repository_button: true
  use_issues_button: true
  baseurl: https://jorisparet.github.io/partycls/docs/tutorial/